export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_STUDENT = 'GET_STUDENT';

export const DELETE_BOOK = 'DELETE_BOOK';
export const DELETE_BOOKCAT = 'DELETE_BOOKCAT'

export const GET_BOOKS = 'GET_BOOKS';
export const GET_BOOKCAT = 'GET_BOOKCAT';
export const FETCH_BOOKCAT = 'FETCH_BOOKCAT';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const DELETE_STUDENT = 'DELETE_STUDENT';


export const GET_ISSUE_BOOKS = 'GET_ISSUE_BOOKS';
